import puppeteer from 'puppeteer-core';
const b=await puppeteer.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:'new',args:['--no-sandbox']});
const p=await b.newPage(); await p.setViewport({width:1440,height:1100,deviceScaleFactor:2});
await p.goto('http://localhost:4366/fi/treats/',{waitUntil:'networkidle0',timeout:90000});
await p.evaluate(()=>{try{localStorage.setItem('laplandgifts_cookie_consent','accepted')}catch(e){}});
await p.reload({waitUntil:'networkidle0'}); await new Promise(r=>setTimeout(r,2000));
const count=()=>p.evaluate(()=>document.querySelectorAll('a[href*="/product/"]').length);
console.log('ei valintaa:', await count());
await p.select('select', 'US'); await new Promise(r=>setTimeout(r,1200));
console.log('US:', await count());
await p.select('select', 'DE'); await new Promise(r=>setTimeout(r,1200));
console.log('DE:', await count());
await p.select('select', ''); await new Promise(r=>setTimeout(r,1200));
await p.screenshot({path:'../_shots/v5-treats.png'});
const p2=await b.newPage(); await p2.setViewport({width:1440,height:1100,deviceScaleFactor:2});
await p2.goto('http://localhost:4366/fi/product/moomin-wild-blueberry-coffee/',{waitUntil:'networkidle0',timeout:90000});
await new Promise(r=>setTimeout(r,2000));
const note=await p2.evaluate(()=>{const el=[...document.querySelectorAll('p,div')].find(e=>/ei toimiteta|toimiteta näihin/i.test(e.textContent||'')); return (el?.textContent||'EI LOYDY').trim().slice(0,180)});
console.log('rajausteksti:', note);
await p2.screenshot({path:'../_shots/v5-moomin.png'});
await b.close();
